credentials:
  usernames:
    user:
      email: pchichghare@synoptek.com
      name: User
      password: $2b$12$aK93RlYQSUYga1FzLnLMSePV.l0h5S79pubZPzQjRExz0zrmTy9bq
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name