cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: nasingh@synoptek.com
      name: Admin
      otp_secret: 5HQIQS5ODU5ZASVW5DINUTEWWVUATFRN
      password: $2b$12$.XZiG7ol4iOW0NI1ceL.SO9JAxzGJhbB5GPfSrFTxaH6c9zmM4YY.
    apurohit:
      email: apurohit@synoptek.com
      name: Anish
      otp_secret: null
      password: $2b$12$nFKQMpcr6uQrOwvi8QV/B.NrvDOEpcj1kZRsVHd25y9gT0m/KHNl2
    awills:
      email: awills@synoptek.com
      name: Andrew
      otp_secret: null
      password: $2b$12$12gcBW9iJg9lLe2bgKEs9.3t.qLI9kPPFZfFFymPvB65rHFaYOEjC
    chayden:
      email: chayden@synoptek.com
      name: Chris
      otp_secret: null
      password: $2b$12$kDj/N6vDfa8FRyg8FeWS4OFSxWsRpENzkcGV3bULF7.qtRjGbizAi
    cmccarthy:
      email: cmccarthy@synoptek.com
      name: Christopher
      otp_secret: null
      password: $2b$12$noXmbOJSn.tLpLIGaBwz1.rSS1PqkykDW664LXylOJiXAvXvhTU.G
    criley:
      email: criley@synoptek.com
      name: Chris
      otp_secret: null
      password: $2b$12$OukUwBntyjWu9HhHvjM3FuVwVnrOLu2plPXqzMWA2A37jeCrOpOTi
    gfenton:
      email: gfenton@synoptek.com
      name: George
      otp_secret: null
      password: $2b$12$BhVwjHqLktcmqcMMatIeL.2xB4EGjATfLKTQ6kHpsVe3uRR27k7zG
    hvshah:
      email: hvshah@synoptek.com
      name: Hardik
      otp_secret: null
      password: $2b$12$GPhfkoGMw4UCSDo5hAOPS.aF.84O20xwG8Z7eI425UEk2uvbLvxMa
    jcann:
      email: jcann@synoptek.com
      name: Jay
      otp_secret: null
      password: $2b$12$TsHN2elv8skikJzm46HxwezhnKTE4pHwDS2y0/ZaeG2TVawQMFRRK
      totp_secret: ''
    jcarey:
      email: jcarey@synoptek.com
      name: Joseph
      otp_secret: null
      password: $2b$12$fDBp6O7qwB.CPnSZX7yhPuK360mow85djYYs0.4SPlaLAgOt9SMi6
    mmoffatt:
      email: mmoffatt@synoptek.com
      name: Michael
      otp_secret: null
      password: $2b$12$At8aZpoDfXrxZmOJ0HVpX.Ghn55qK79CXP7gbHXbxf0eRDMdDqkwi
    msanchez:
      email: msanchez@synoptek.com
      name: Miguel
      otp_secret: null
      password: $2b$12$bJ0ube1F7alRDToqyg8DNeQhuJC6FWl.YGAWxGZUMMtCPRzbVxVBu
    mthakkar:
      email: mthakkar@synoptek.com
      name: Manan
      otp_secret: null
      password: $2b$12$Wm1dgUKqSZaADrjG6hx7s.dXLZtcyYAqjJqrnw8it1qia00byjeR6
    nasingh:
      email: nasingh@synoptek.com
      name: Naman
      otp_secret: null
      password: $2b$12$p2lwHpaa4rwvNA0vCW7NrOzZy4YlD1C/rWxoBAgQnPZton0pQCZ1y
      totp_secret: null
    pchichghare:
      email: pchichghare@synoptek.com
      name: Pawan
      otp_secret: null
      password: $2b$12$c.rjKVU9kn4Bqtk69bncUOy4xjr/VKp0QdCe/zX2jaTHIYD5Q9XnC
    rroger:
      email: rroger@synoptek.com
      name: Rohan
      otp_secret: null
      password: $2b$12$f6In3ucwA2Wkj4v5inIpKeK7yxwaKu3znEOj.5iZ60pKG5w5ChGwy
    scurrie:
      email: scurrie@synoptek.com
      name: Stephen
      otp_secret: null
      password: $2b$12$S8ugUVHK.wIqyyDvcCF.D.0dLiTxaCfx8WOVXsxZ1glt6m0ZKjoea
      totp_secret: ''
    sgahlot:
      email: sgahlot@synoptek.com
      name: Shubhankar
      otp_secret: null
      password: $2b$12$t/qaxVS9A2aJEbWy5jK5KukfFxQ9uYzoga7YciOQ9SGKCPkThsKs.
    sryan:
      email: sryan@synoptek.com
      name: Sean
      otp_secret: null
      password: $2b$12$KoeXjLDowR2/hTNIBvCQZOIU3G5Oh82cf8L7wTWGLNPxd5CjykHTy
    tbecker:
      email: tbecker@synoptek.com
      name: Tim
      otp_secret: null
      password: $2b$12$VhPoHzqhxaAfOfCg6veA7Oy1qKRDH0OwD.DMWNWJk7xkjgvZyq/UO
    tbritt:
      email: tbritt@synoptek.com
      name: Timothy
      otp_secret: null
      password: $2b$12$PkvR/VCervsW.1zAMAhAT.e8M04TIObD9VR2WTOKe7O7ju9ATGt8m
    test:
      email: pchichghare@synoptek.com
      name: Test
      otp_secret: null
      password: $2b$12$hM5iN6B4DRM485L3KNrHJ.jEcUgsmkj9I9xURX9MHilfaAnv2XcsG